name: go
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1
      - uses: actions/checkout@v3
      - run: go build ./...
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1
      - uses: actions/checkout@v3
      - run: go test -cover -run=. -bench=. -benchmem ./...
